[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[[commands]]
name = "seed"
command = "/start.sh seed"
description = "Seed test data"

[[commands]]
name = "update"
command = "/start.sh update"
description = "Update test data"

[[commands]]
name = "rollback"
command = "/start.sh rollback"
description = "Rollback test data"

[[commands]]
name = "status"
command = "/start.sh status"
description = "Check test data status"

