[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "start"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[[commands]]
name = "seed"
command = "start seed"
description = "Seed test data"

[[commands]]
name = "update"
command = "start update"
description = "Update test data"

[[commands]]
name = "rollback"
command = "start rollback"
description = "Rollback test data"

[[commands]]
name = "status"
command = "start status"
description = "Check test data status"

